### ISSUE TITLE
Removing user heralds.

### ISSUE THREAD

**Issue by weylin** [snoonetIRC/CloudBot#2]
Hello,

OP/HOP do not have a method to remove other user heralds. 

Thank you,
Weylin-

**Comment by JacobCallahan** [comment]
suggested syntax ```.herald remove SomeNick```

**Comment by edwardslabs** [comment]
Currently in CloudBot there is no way to determine what users in a channel have OP/HOP access and then assign permissions based on those access levels. 

It is something I would very much like to implement and once that is implemented this is something that would be quite easy to do. I will leave this open dependent on tracking user access levels.

**Comment by JacobCallahan** [comment]
could that be accomplished by having the bot execute !flags and verify user status that way?

**Comment by edwardslabs** [comment]
That particular solution won't work because it would then require the bot to either be an irc operator or rely on having the proper access to run !flags in every channel it is in. 

The problem is keeping track of everyone in every channel including nick changes, access mode changes, joins, parts, disconnects, removes, kicks, etc. This way there is a cache of who is in and has access to things in each channel that can be stored in a variable.

Otherwise every time the command is run it would have to parse the output of /who #channel.

**Comment by edwardslabs** [comment]
This functionality is now implemented for Snoonet staff thanks to @typoguy.
